version: '3.8'
services:
  db: 
    image: mariadb:lts-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=php_docker
      - MARIADB_USER=gerardo
      - MARIADB_PASSWORD=password
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www: 
    image: php:apache
    volumes:
      - "./www:/var/www/html"
    ports:
      - "8080:80"
      - "443:443"
    # Custom command to install the mysqli extension and start Apache.
    command: >
      bash -c "docker-php-ext-install mysqli && 
      apache2-foreground"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    
